const TRANSLATE_VOICE_MAPPING = {
	'ar': 'Maged', 
 	'cs': 'Zuzana',
 	'da': 'Sara', 
 	'de': 'Anna',
 	'el': 'Melina',
	'en': 'Samantha',
 	'es': 'Jorge',
 	'fi': 'Satu',
 	'fr': 'Thomas',
 	'hi': 'Lekha',
 	'hu': 'Mariska',
 	'id': 'Damayanti',
 	'it': 'Luca',
 	'iw': 'Carmit',
 	'ja': 'Kyoko',
 	'ko': 'Yuna',
 	'nl': 'Xander',
 	'pl': 'Zosia',
 	'pt': 'Joana',
 	'ro': 'Ioana',
 	'ru': 'Milena',
 	'sk': 'Laura',
 	'sv': 'Alva',
 	'th': 'Kanya',
 	'tr': 'Yelda',
 	'zh-CN': 'Ting-Ting',
 	'zh-HK': 'Sin-ji'
}

export default TRANSLATE_VOICE_MAPPING